### ISSUE TITLE
Clean out Travis build matrix to speed up CI

### ISSUE THREAD

**Issue by jesperronn** [jmazzi/crypt_keeper#114]
This innocent looking support matrix in [.travis.yml](https://github.com/jmazzi/crypt_keeper/blob/master/.travis.yml#L3)  is very deceptive
```
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1

gemfile:
  - gemfiles/activerecord_3_1.gemfile
  - gemfiles/activerecord_3_2.gemfile
  - gemfiles/activerecord_4_0.gemfile
  - gemfiles/activerecord_4_1.gemfile
  - gemfiles/activerecord_4_2.gemfile

matrix
  include:
    - rvm: 2.2.0
      gemfile: gemfiles/activerecord_4_2.gemfile
```

this runs 3x5+1 = 16 jobs and takes 21 minutes before you get feedback after commit.

We also need to add newer ruby versions: 2.3.0 at least, and the upcoming rails 5 version.

Any suggestions as to which jobs should be weeded out to make space for newer versions?
